
[package]
name = "whitebox_tools"
version = "0.3.1"
authors = ["John Lindsay <jlindsay@uoguelph.ca>"]
description = "A library for analyzing geospatial data."
keywords = ["geospatial", "GIS", "geomatics", "lidar", "spatial analysis"]
readme = "README.md"
repository = "https://github.com/jblindsay/whitebox-geospatial-analysis-tools/whitebox_tools/"
# documentation = "http://www.uoguelph.ca/~hydrogeo/software.shtml"
license = "MIT"

# [lib]
# name = "whitebox_tools"
# crate-type = ["dylib"]
# # crate-type = ["rdylib"]
# # crate-type = ["rlib"]
# # crate-type = ["staticlib"]
# path = "src/lib.rs"

# [[bin]]
# name = "whitebox_tools"
# path = "src/main.rs"

# [profile.release]
# panic = 'abort'

# The release profile, used for `cargo build --release`.
# [profile.release]
# opt-level = 3
# debug = false
# rpath = false
# lto = false
# debug-assertions = false
# codegen-units = 1
# panic = 'unwind'

[dependencies]
byteorder = "^1.1.0"
kdtree = "^0.3.1"
nalgebra = "^0.10.1"
num_cpus = "^1.2.1"
rand = "^0.3.15"
serde = "1.0.19"
serde_derive = "1.0.19"
serde_json = "1.0.6"
statrs = "0.8.0"
time = "^0.1.35"
zip = "0.2.5"
