
[package]
name = "whitebox_tools"
version = "0.6.0"
authors = ["John Lindsay <jlindsay@uoguelph.ca>"]
description = "A library for analyzing geospatial data."
keywords = ["geospatial", "GIS", "remote sensing", "geomatics", "image processing", "lidar", "spatial analysis"]
readme = "README.md"
repository = "https://github.com/jblindsay/whitebox-geospatial-analysis-tools/whitebox_tools/"
license = "MIT"

# [lib]
# name = "whitebox_tools"
# crate-type = ["dylib"]
# # crate-type = ["rdylib"]
# # crate-type = ["rlib"]
# # crate-type = ["staticlib"]
# path = "src/lib.rs"

# [[bin]]
# name = "whitebox_tools"
# path = "src/main.rs"

# [profile.release]
# panic = 'abort'

# The release profile, used for `cargo build --release`.
[profile.release]
codegen-units = 16
# opt-level = 3
# debug = false
# rpath = false
# lto = false
# debug-assertions = false
# panic = 'unwind'

[dependencies]
byteorder = "^1.1.0"
kdtree = "0.4.0"
nalgebra = "0.14.0"
num_cpus = "1.6.2"
rand = "0.4.2"
serde = "1.0.19"
serde_derive = "1.0.19"
serde_json = "1.0.9"
statrs = "0.9.0"
time = "^0.1.37"
zip = "0.3.0"
